#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/dafault
# Configure Nginx to listen on port 80 for all active IPV$ IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
