#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

# create a symbolic link 9-s option) between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminates the first process ID
kill "$(pgrep 'nginx' | head -1)"
